### PR TITLE
Static side generation

### PR DESCRIPTION
**Pull request by DerProfi**
Why? 
To learn more about SSG.

What?
Since the search/ routing itself relies on JS, I added the squad members to the landing page and created an own page for each of them, which are statically generated.

### CODE REVIEW

**Comment by viniciuskneves** [comment]
Hey @DerProfi I just took a look into it and I think you didn't fully get the idea behind SSG and Nuxt.

You don't need to create the pages for us individually, otherwise you're repeating a lot of code. Check for https://nuxtjs.org/docs/features/nuxt-components/#the-nuxtlink-component and let me know if you need help.

By the end this edit should be enough:
```html
<nuxt-link to="/user/viniciuskneves"> <p>Vini</p></nuxt-link>
```

**Comment by DerProfi** [comment]
> Hey @DerProfi I just took a look into it and I think you didn't fully get the idea behind SSG and Nuxt.
> 
> You don't need to create the pages for us individually, otherwise you're repeating a lot of code. Check for https://nuxtjs.org/docs/features/nuxt-components/#the-nuxtlink-component and let me know if you need help.
> 
> By the end this edit should be enough:
> 
> ```
> <nuxt-link to="/user/viniciuskneves"> <p>Vini</p></nuxt-link>
> ```

Hey @viniciuskneves, thank you for having a look. I got mislead by the information that nuxt link wouldn't work without JS and this seemed like the only solution to make the app SSG. 
Awesome news, this opens even more possibilities. Thanks again.

**Comment by viniciuskneves** [comment]
Really cool!

The idea is: Nuxt will take care of rendering the page for you, you don't need to add any extra steps (in general, check https://github.com/homeday-de/website/blob/master/nuxt.config.js#L21-L37).

I will also propose a challenge: try removing the store from your application 😅
It is not needed so if you've time, try to do it. Store is cool and useful when you need to share data in a bunch of places but your application only needs user data in the user view.
At the website project we don't use store at all, even though we have a lot of data flowing throughout the application.

**Review by viniciuskneves — APPROVED** [review]
Go for it!

**Pull request merged**
